### PR TITLE
get something into master

### PR DESCRIPTION
**Pull request by JParisFerrer**
I have not really carefully reviewed this code, but I think it would be a good idea to get something down in master so that if someone decides they want to take a look at something they can PR regularly, etc.

We could even push code rewrites into PRs after this, or we update this PR, idk.

### CODE REVIEW

**Comment by Binary-Eater** [comment]
Thanks for setting this up. Want to convert some of the code to using `async` functions and see if I can clean up the nested callbacks in the code. Other than that, I would say its pretty reasonable to merge in actually. I think @nwalters512 had some points in general that he considered bringing up last time. I think the nested callbacks and UI need cleanup but that can probably be done even after merging into master.

**Review by Binary-Eater — APPROVED** [review]
Seems to be well done. Like those async functions :+1:

**Comment by Binary-Eater** [comment]
I do think we should consider rewriting all the JS files as CoffeeScript however.

**Review by PiotrGalusza — APPROVED** [review]
No issues found, should be good to merge :)

**Pull request merged**
